name: Run Tests

on: 
    pull_request:
        branches:
            - main


jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Setup python  
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
            cache: 'pip'
            
        - name: Install requirements
          run: pip install -r requirements.txt
              
        - name: Run tests 
          run: python3 -m pytest test_*.py